name: standard workflows...

on:
  push:
    branch: [ main ]
  pull_requests:
    branch: [ main ]

jobs:
  stable:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with: 14.x
      - name: installing packages
        run: npm ci
      - name: running tests
        run: npm run test